### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by pyni** [ylabbe/cosypose#10]
Hi, i run the code:python -m cosypose.scripts.run_cosypose_eval --config ycbv
it shows:
No such file or directory: '/home/yuan/doc/objectpose/cosypose/local_data/bop_datasets/ycbv/test'
And it seems that ycbv has not test file:
![Screenshot from 2020-10-16 22-21-30](https://user-images.githubusercontent.com/18031767/96270252-f8c90c00-0ffd-11eb-8612-fde4861e9fc3.png)

So do you have any suggestion for this case?

**Comment by ylabbe** [comment]
Hi,

You need to download the YCB dataset in BOP format. I see you have downloaded the additional files but not the original dataset. You can use this command:
```
python -m cosypose.scripts.download --bop_dataset=ycbv
```

**Comment by pyni** [comment]
Yes! 
 Maybe that is problem of my network.
Thanks for quickly reply.
