### ISSUE TITLE
Error: No folder named models in tless dataset folder

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [ylabbe/cosypose#14]
Hi, I have downloaded tless dataset and was trying to run:
```bash
python -m cosypose.scripts.run_bop_inference --config bop-synt+real --nviews=1
```
The following error occurs:
```python
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/Documents/Code/cosypose/local_data/bop_datasets/tless/models/models_info.json'
```
In the tless dataset folder, the name of models are `models_cad`, `models_eval`, and `models_reconst`, should I just change the name of `models_eval` to `models`? Thanks.

**Comment by ylabbe** [comment]
you can symlink `models_eval` to `models` yes

**Comment by Lynne-Zheng-Linfang** [comment]
Thanks.
