### ISSUE TITLE
Difference between posecnn and posecnn_init/external_coarse?

### ISSUE THREAD

**Issue by Uio96** [ylabbe/cosypose#18]
Hi, thanks for your good work.

I am checking your single view result on ycb-video dataset by taking a look at your 'ycbv-n_views=1--5154971130' result posted online. I am wondering the difference between posecnn and posecnn_init/external_coarse. It is obvious that posecnn result can directly borrow from their result as you mentioned in the paper. But what does posecnn_init/external_coarse do based on that? Do you run your CNN coarse network on it or something else? I am curious because when I visualize some of the views, posecnn_init/external_coarse will give me more predictions than posecnn. For example, for scene 49, view 785,
posecnn_init/external_coarse will give me the following one
![posecnn_init_external_coarse](https://user-images.githubusercontent.com/13082153/99075252-2c5c6f00-2587-11eb-9cd2-45793248541e.png)

while posecnn's result is here:
![posecnn](https://user-images.githubusercontent.com/13082153/99075400-688fcf80-2587-11eb-8499-681b852c1881.png)

I assumed posecnn_init_external_coarse would only refine the posecnn result a little bit rather than predict something new. 

Could you help me understand the process? Thank you so much.

By the way, here is part of the result from 'ycbv-n_views=1--5154971130':

> OrderedDict([('posecnn',
              PandasTensorCollection(
                  poses: torch.Size([493920, 4, 4]) torch.float32 cpu,
                  bboxes: torch.Size([493920, 4]) torch.float32 cpu,
              ----------------------------------------
                  infos:
                      scene_id  view_id  score       label  batch_pred_id
              0             48        1    1.0  obj_000001              0
              1             48        1   20.0  obj_000020              1
              2             48        1   14.0  obj_000014              2
              3             48        1   19.0  obj_000019              3
              4             48        1    6.0  obj_000006              4
              ...          ...      ...    ...         ...            ...
              493915        59     1857   15.0  obj_000015          15430
              493916        59     1857    6.0  obj_000006          15431
              493917        59     1857    9.0  obj_000009          15432
              493918        59     1857    4.0  obj_000004          15433
              493919        59     1857   18.0  obj_000018          15434
              [493920 rows x 5 columns]
              )),
             ('posecnn_init/external_coarse',
              PandasTensorCollection(
                  poses: torch.Size([15435, 4, 4]) torch.float32 cpu,
                  bboxes: torch.Size([15435, 4]) torch.float32 cpu,
              ----------------------------------------
                  infos:
                     scene_id  view_id  score       label  det_id  batch_im_id  group_id
              0            48      733    1.0  obj_000001     342            0        92
              1            48      733   20.0  obj_000020     343            0        92
              2            48      733   14.0  obj_000014     344            0        92
              3            48      733    6.0  obj_000006     345            0        92
              4            48      733   21.0  obj_000021     346            0        92
              ...         ...      ...    ...         ...     ...          ...       ...
              15430        59      561    2.0  obj_000002   14151            0      2732
              15431        59      561    9.0  obj_000009   14152            0      2732
              15432        59      561    6.0  obj_000006   14153            0      2732
              15433        59      561    4.0  obj_000004   14154            0      2732
              15434        59      561   18.0  obj_000018   14155            0      2732
              [15435 rows x 7 columns]
              )),

**Comment by ylabbe** [comment]
Hi,

Are you sure that you took the predictions for the same image ? You need to get the correct `scene_id` and `view_id` in each tensor collections. You can't just get the same index in both because they have different size. The posecnn tensor collection has more detections because all predictions are gathered from each process and each process loads all the posecnn results `posecnn_init` but only selects the image that the process runs inference on in `posecnn_init/external_coarse`. Evaluation is run using 32 process which is why you have `493290=15435*15`.

**Comment by Uio96** [comment]
Thank you so much for the quick response.

Yep. I am using your provided visualization code, so they should be the result of the same scene_id and view_id. 
```
scene_id, view_id = 49, 785
this_preds = filter_predictions(results[pred_key], scene_id, view_id)
```
I just changed the pred_key like:
```
# pred_key = 'posecnn_init/external_coarse'
pred_key = 'posecnn'
```

**Comment by ylabbe** [comment]
Thanks for pointing this out. I think this is a rendering bug because `posecnn` has the duplicates and has to render something like 5 * 32 objects and it goes outside of bullet memory limits for the assets. Can you try to remove the duplicates from `posecnn` that come from the multiprocessing (there `posecnn` predictions are not used/evaluated anywhere`) and  see if that solves the problem ?

**Comment by Uio96** [comment]
No, I do not think so. 

As you can see there, the result of ```posecnn``` is fine even if it has many more results (many duplicates as you pointed out).  Instead, the result of  'posecnn_init/external_coarse' is wired. Actually  'posecnn_init/external_coarse' and its afterward refined result are consistent that both of them have additional predictions compared with the original posecnn one.

So I do not think it has something to do with the rendering stuff but the result itself may not be correct.

**Comment by ylabbe** [comment]
Here I just take the remove the dupliactes of `posecnn` and render them, it looks like `posecnn_init/external_coarse` ?

![image](https://user-images.githubusercontent.com/14931236/99130948-121ba300-2612-11eb-85e8-3e3eb9a97a8b.png)

**Comment by Uio96** [comment]
So you mean that the render did not output some of the results for ```posecnn``` because of the potential bug of render (it can not deal with so many duplicates)?

Sorry, I do not fully understand your points earlier. Thank you so much for the quick answer. The posecnn result is worse than I once expected :)

**Comment by ylabbe** [comment]
> So you mean that the render did not output some of the results for posecnn because of the potential bug of render (it can not deal with so many duplicates)?

Yes, but its not potential, i've had this problem before when trying to render too many objects.
