### ISSUE TITLE
TypeError: get_predictions() got an unexpected keyword argument 'use_gt_detections'

### ISSUE THREAD

**Issue by Hao-HUST** [ylabbe/cosypose#20]
Hi, thanks for sharing.

When I try to train the coarse and refiner model for tless dataset, by running 

>  python -m cosypose.scripts.run_pose_training --config tless-coarse
    python -m cosypose.scripts.run_pose_training --config tless-refiner

the error occured 

> TypeError: get_predictions() got an unexpected keyword argument 'use_gt_detections'.

More details are list as follow:

> 100%|██████████████████████████| 3600/3600 [32:45<00:00,  1.83it/s, loss=0.0718]
> 100%|█████████████████████████████████████████| 360/360 [01:51<00:00,  3.22it/s]
> Prediction : pix2pose_detections
> Traceback (most recent call last):
  > File "/home/hao/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
 >  File "/home/hao/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
  > File "/home/hao/project/cosypose/cosypose/scripts/run_pose_training.py", line 207, in <module>
  >   train_pose(cfg)
 >  File "/home/hao/project/cosypose/cosypose/training/train_pose.py", line 359, in train_pose
 >    test_dict = test()
 >  File "/home/hao/anaconda3/envs/cosypose/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
   >  return func(*args, **kwargs)
  > File "/home/hao/project/cosypose/cosypose/training/train_pose.py", line 351, in test
    > return run_eval(eval_bundle, epoch=epoch)
  > File "/home/hao/project/cosypose/cosypose/training/train_pose.py", line 182, in run_eval
   >  results = run_pred_eval(pred_runner, pred_kwargs, eval_runner)
  > File "/home/hao/project/cosypose/cosypose/evaluation/runner_utils.py", line 15, in run_pred_eval
    > preds = pred_runner.get_predictions(**pred_kwargs_n)
> TypeError: get_predictions() got an unexpected keyword argument 'use_gt_detections'

Any suggestions about that?

**Comment by azad96** [comment]
@Hao-HUST, could you find a solution? I am getting the same error.

**Comment by Hao-HUST** [comment]
> @Hao-HUST, could you find a solution? I am getting the same error.

Not yet, i am also still waiting for responding.

**Comment by azad96** [comment]
@Hao-HUST, I may have a workaround for this problem. The `get_predictions()` method of MultiviewPredictionRunner class does not have a parameter named `use_gt_detections` as the error says. I removed this parameter from where it is defined, so I made the following change in line 106 in train_pose.y
~~~
base_pred_kwargs = dict(
    pose_predictor=predictor,
    mv_predictor=None,
    # use_gt_detections=False,
    skip_mv=True,
)
~~~

Then, you get another error saying `AttributeError: 'Namespace' object has no attribute 'init_method'`. I checked the setup in run_pose_training.py and for tless- models there is no cfg.init_method defined. It is only defined for bop- models, so I added a dummy one. This time I made the following change in line 135 in run_pose_training.py
~~~
if args.config == 'tless-coarse':
    cfg.TCO_input_generator = 'fixed'
    cfg.init_method = 'no-init-method' # added
elif args.config == 'tless-refiner':
    cfg.TCO_input_generator = 'gt+noise'
~~~

After these changes I managed to handle the problems. Hope this works for you too.

**Comment by ylabbe** [comment]
Hi, this should be fixed in https://github.com/ylabbe/cosypose/commit/291d2c5af1ff21008f0f464a2243b0a532182404.
