### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by eagleeye05** [ylabbe/cosypose#24]
Hi, when I run : python -m cosypose.scripts.run_cosypose_eval --config ycbv, something is wrong.
I have download ycb video and related files.
![image](https://user-images.githubusercontent.com/58255653/100301432-13b27700-2fd3-11eb-81f6-cbdb8190e228.png)

Could you give me some advice? Thanks!

**Comment by ylabbe** [comment]
Running the following command in `local_data` and running the script again should fix it:
```
rm -rf joblib_cache/cosypose/datasets/bop/build_index/
```
