### ISSUE TITLE
Unable to run single-image evaluation or training on TLESS -- tless/models/models_info.json is missing?

### ISSUE THREAD

**Issue by roboticsbrian** [ylabbe/cosypose#26]
Running the single-image evaluation script on TLESS fails with 
```
FileNotFoundError: [Errno 2] No such file or directory: '/cosypose/local_data/bop_datasets/tless/models/models_info.json'                                                
```
I am able to run single-image evaluation on the YCBV dataset successfully, but not TLESS.

**Comment by roboticsbrian** [comment]
Solved by https://github.com/ylabbe/cosypose/issues/14. 
TL;DR symlink `models_eval` to `models`

**Comment by ylabbe** [comment]
Thanks for pointing out this bug. Fixed in https://github.com/ylabbe/cosypose/commit/8e284acc39b13c7a172164ad0f482e3c1c83ca0d.

Running `python -m cosypose.scripts.download --bop_extra_files=tless` will create the symlink.
