### ISSUE TITLE
No Such File Error in Reproducing Single-View Results

### ISSUE THREAD

**Issue by azad96** [ylabbe/cosypose#28]
Hi, I downloaded the TLESS dataset from the BOP challenge's [website](https://bop.felk.cvut.cz/datasets/). However, when execute the command below
`
python -m cosypose.scripts.run_cosypose_eval --config tless-siso
`
I got the following key error

![Screenshot from 2020-12-17 23-39-44](https://user-images.githubusercontent.com/39907647/102542306-a4581080-40c2-11eb-8c38-740af38cf9a6.png)
Folders inside the local_data/bop_datasets/tless/test_primesense do not start with the prefix 'obj_', so I renamed all of them by adding the prefix. However, this time I got the following error
![Screenshot from 2020-12-17 23-41-45](https://user-images.githubusercontent.com/39907647/102542488-f00aba00-40c2-11eb-8fd4-b23e3fc79b48.png)

Anyone knows the reason of this error? Thanks in advance.

**Comment by ylabbe** [comment]
Are you sure you downloaded the BOP tless dataset correctly ? Does the file `.../tless/test_primesense/000003/rgb/000353.png` exists ?

**Comment by azad96** [comment]
@ylabbe, I checked know and it exists. Should the folder name be 000003 or obj_000003? Because I renamed 000003 as obj_000003 and also other 19 folders. Othewise I get the first error I mentioned before which is KeyError: 'obj_000018'

**Comment by azad96** [comment]
I downloaded the files using your script. I have 30 ply files instead of 15 now and I do not get this error anymore.
