### ISSUE TITLE
git lfs pull giving error

### ISSUE THREAD

**Issue by acube3** [ylabbe/cosypose#30]
git lfs pull is giving the following error:
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/ylabbe/cosypose.git/info/lfs'

Could you please increase the quota or provide another way to get to the repository?
Thanks.

**Comment by ylabbe** [comment]
hi, this is fixed
