### ISSUE TITLE
What's in the keyframe.txt of ’ycbv‘ and why?

### ISSUE THREAD

**Issue by auto-fly** [ylabbe/cosypose#31]
Sorry to disturb you, I am looking at your paper and mode your code, for the file“ keyframe.txt ”I don't know much about the content and use of. Hope you can answer. Thank you again!

**Comment by ylabbe** [comment]
Hi, this file defines the test images used by PoseCNN.

**Comment by auto-fly** [comment]
I see. Thank you very much for your reply!


| |
leepengchao
|
|
m17335853581@163.com
|
签名由网易邮箱大师定制
On 1/4/2021 21:48，Yann Labbé<notifications@github.com> wrote：

Hi, this file defines the test images used by PoseCNN.
