### ISSUE TITLE
Coarse and Refiner

### ISSUE THREAD

**Issue by botanyldrm** [ylabbe/cosypose#34]
I have a small question which is not related to repository but paper. Can you explain difference of coarse and refiner models with a  sentence? 

As I understand, both model use same architecture and both of them applicable to single view prediction.  In both of them, number of iteration for iterative improvement can be set to a number higher than 1. Coarse model initial pose estimations for rendering is set such that camera is located at the center of object in x-y dimension and distance between them in z-dimension is 1m. But as I understand this is different for refiner model, refiner model use predictions from a coarse model. So is the only difference between them is initialization of TCO?

**Comment by ylabbe** [comment]
Your interpretation is correct and during training the only difference between coarse and refiner is the distribution of errors between the input and ground truth poses.

**Comment by botanyldrm** [comment]
I have one final question. Test and training processes for refiner model is different, right? During training TCO for refiner coming from ground truth and then, we add noise for both rotation and translation. During test, we use coarse model prediction for refiner model TCO initialization without any noise.

**Comment by ylabbe** [comment]
Yes, the noise added to ground truth TCO during training of the refiner is to simulate the errors of the coarse model that the refiner network is going to see at test time.
