### ISSUE TITLE
Unable to download BOP challenge datasets

### ISSUE THREAD

**Issue by SelvamArul** [ylabbe/cosypose#40]
I am not sure if this is the right place to report an issue. But I am unable to download BOP challenge datasets from the links provided.  The download links provided in the download script and the BOP challenge webpage could not be reached.
![image](https://user-images.githubusercontent.com/7311434/107879590-0756ff80-6eda-11eb-976f-bfe7bf3c23d0.png)

![image](https://user-images.githubusercontent.com/7311434/107879625-3f5e4280-6eda-11eb-9b51-01d103c9e43b.png)

The google drive directory also does not contain the dataset.
Could you please provide me with an alternative link to download the dataset?

**Comment by mohammad-h-b** [comment]
I have the same problem in cloning the repo:
```
Cloning into 'cosypose'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 283 (delta 48), reused 56 (delta 28), pack-reused 196
Receiving objects: 100% (283/283), 46.39 MiB | 4.57 MiB/s, done.
Resolving deltas: 100% (59/59), done.
git-lfs filter-process: 1: git-lfs filter-process: git-lfs: not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by Toefinder** [comment]
> The google drive directory also does not contain the dataset. Could you please provide me with an alternative link to download the dataset?

@SelvamArul The link to download BOP is updated to https://bop.felk.cvut.cz/datasets/, referenced from [this issue comment](https://github.com/ylabbe/cosypose/issues/76#issuecomment-1256271757 )
