### ISSUE TITLE
Configuration with runjob-config

### ISSUE THREAD

**Issue by yupei-git** [ylabbe/cosypose#48]
Hello, when I got to the '**Training details**' in the '**BOP20 models and results**' section, using
`'runjob --ngpus=1 python -m cosypose.scripts.run_detector_training --config bop-ycbv-synt+real'` to train the ycbv dataset on the synthetic + real image, the problem occurs![Screenshot from 2021-04-26 18-10-10](https://user-images.githubusercontent.com/73900103/116119653-f4716000-a6be-11eb-9c88-421baa208337.png)

I modified the **job-runner-config.yaml**, as shows:

![Screenshot from 2021-04-26 18-11-15](https://user-images.githubusercontent.com/73900103/116119845-27b3ef00-a6bf-11eb-9a9d-5be3adfb9cbe.png)
and used '`runjob-config job-runner-config.yaml`', but got the same error.

Before that, the '**Installation**' and '**Downloading and preparing data**' sections were successfully completed. Since I wanted to do it with a single local GPU, I just used the command line '`export CUDA_VISIBLE_DEVICES=0`' and '`python -m cosypose.scripts.example_multigpu`' in the '**Note on GPU parallization**' section. But that works in '**Reproducing single-view results**' part.

Could anyone help me with this? Thanks in advance!

**Comment by JohannesAma** [comment]
Hello @yupei-git ,
can you tell me how you solved this ?

**Comment by yupei-git** [comment]
I reinstalled cosypose and the environment. Then copied the local_data from the original cosypose into the new one. When I ran the train again, the above error did not exist.
