### ISSUE TITLE
AttributeError: module 'pinocchio' has no attribute 'Quaternion'

### ISSUE THREAD

**Issue by buaacyw** [ylabbe/cosypose#49]
Thanks for your great work, can you help me to solve the below problem?
cosypose/cosypose/lib3d/transform.py
need pinocchio  2.3.1 
so I download it here https://anaconda.org/conda-forge/pinocchio/files?version=2.3.1

But when I ran transform.py

I got :
AttributeError: module 'pinocchio' has no attribute 'Quaternion'

in pinocchio'document from github https://github.com/stack-of-tasks/pinocchio

I can't find Quaternion too. What's wrong?

**Comment by hillaric** [comment]
Hello, do you solve this problem?

**Comment by jcarpent** [comment]
Just take the latest version of pinocchio=2.6.1, it should work.

**Comment by hillaric** [comment]
thanks
