### ISSUE TITLE
The link is not available

### ISSUE THREAD

**Issue by yupei-git** [ylabbe/cosypose#51]
Hello, in the "Training a single-view 6D pose estimation model" section, the link to the notebook at "Visualizing images of the dataset" is not available. 
![Screenshot 2021-04-30 at 15 13 14](https://user-images.githubusercontent.com/73900103/116700470-1886b700-a9c7-11eb-946e-bbf89067ec7f.png)
Thanks in advance!

**Comment by swtyree** [comment]
I was just about to report this myself. In both cases, the current/incorrect link is to a non-existent `.py` file but should be to a `.ipynb` file. Just replacing the extension in both links yields the correct file.

`https://github.com/ylabbe/cosypose/blob/master/notebooks/inspect_dataset.py` should be
`https://github.com/ylabbe/cosypose/blob/master/notebooks/inspect_dataset.ipynb`

and

`https://github.com/ylabbe/cosypose/blob/master/notebooks/render_dataset.py` should be
`https://github.com/ylabbe/cosypose/blob/master/notebooks/render_dataset.ipynb`

**Comment by yupei-git** [comment]
Thank you for your help!
