### ISSUE TITLE
Evaluating on custom dataset

### ISSUE THREAD

**Issue by hannes56a** [ylabbe/cosypose#65]
Hi all,
I would like to evaluate on a custom dataset. I tried to use the "run_cosypose_eval.py", but struggled. Are there any hints about that?

**Comment by hannes56a** [comment]
Hey, its me again.
While evaluation (run_cosypose_eval.py" I need a *.pkl file (for e.g. tless located in "saved_detections"). For eval on my custom dataset i do not have such a pkl file. 
Can someone help me please?
- Why does I need this file? I thougt the groundtruth is in the "scene_gt.json" !?
- How can I generate such a file? Is there some script? Does anyone did it allready?
- What is in this file? I think its the groundtruth?

**Comment by FriendlyNature** [comment]
Hi, 
my assumption is, that the pkl file contains the 2D bounding box detections of an independent detection model. Therefore, it is not ground truth data but contains predictions that might be faulty. However, I would also be interested in generating such an file for a custom dataset. Has someone an answer to @hannes56a second question:
> How can I generate such a file? Is there some script? Does anyone did it allready?
