### ISSUE TITLE
RealTime Tracking

### ISSUE THREAD

**Issue by bibekyess** [ylabbe/cosypose#77]
Hi! I am trying to use Cosypose for real-time tracking. But, by referring to run_bop_inference.py, it takes some time to do the inference and it is not realtime inference. I have seen some pose tracking frameworks which are realtime. So, I am just wondering if we can use cosypose for realttime tracking like making 3D bounding box in realtime. If someone has done it before, can you give me some hints?
Thank you!

**Comment by bibekyess** [comment]
I found out that we can use cosypose to do pose estimation in every incoming frame and there is no tracking enabled but the speed is relatively fine while doing multi-object pose estimation. The lag increases as the number of objects increases.

**Comment by Leon998** [comment]
Hi! You said that "the speed is relatively fine while doing multi-object pose estimation", and I wonder which GPU you were using and how much fps can it produce, approximately? Thank you very much
