### ISSUE TITLE
Question regarding Segmentation and Coarse Netwrok

### ISSUE THREAD

**Issue by m13ammed** [ylabbe/cosypose#9]
First of all I congratulate you on the BOP results you have achieved. As I want to test this on my own dataset I the following questions. (I am doing my bachelor thesis and I found your paper very interesting and would like to try it out)

 As written in paper and your implementation that you are using MaskRCNN to get 2D bounding  boxes, does this mean that you are not using the semantic information (semantic/instance pixel segmentation) or that MaskRCNN can be replaced by any proper object detection network (similarly to DeepIM)?

My second question is have you tried using your 2nd and 3rd stage with any pose estimator other than the coarse one you developed (same Arch as the refiner) and PoseCNN?  This question is to have an indication whether I'd need to have an another Architecture for Pose initializer to further enhance the results

**Comment by ylabbe** [comment]
Hi !

> As written in paper and your implementation that you are using MaskRCNN to get 2D bounding boxes, does this mean that you are not using the semantic information (semantic/instance pixel segmentation) or that MaskRCNN can be replaced by any proper object detection network (similarly to DeepIM)?

Instance segmentation masks are only used for ICP depth alignment. For RGB only, MaskRCNN can be replaced by any other 2D detector.

> My second question is have you tried using your 2nd and 3rd stage with any pose estimator other than the coarse one you developed (same Arch as the refiner) and PoseCNN? This question is to have an indication whether I'd need to have an another Architecture for Pose initializer to further enhance the results

I haven't tried other coarse estimation networks beside PoseCNN on YCB-Video.

**Comment by m13ammed** [comment]
Thank you for your quick and useful reply.
